---
- name: create directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - /src
    - /src/etcd-v3.4.17-linux-amd64

- name: Download etcd
  get_url:
    url: '{{ etcd_release_url }}'
    dest: /src/{{ etcd_release_filename }}
    mode: 0644
    checksum: sha256:{{ etcd_release_sha256sum }}

- name: Extract etcd release tarball
  unarchive:
    remote_src: yes
    src: /src/{{ etcd_release_filename }}
    dest: /src/{{ etcd_release_extract_dir }}
    extra_opts: [--strip-components=1]

- name: Link etcd binaries into path
  file:
    src: /src/{{ etcd_release_extract_dir }}/{{ item }}
    dest: /usr/local/bin/{{ item }}
    state: link
  with_items:
    - etcd
    - etcdctl

- name: Create data directory
  file:
    path: /var/lib/etcd
    state: directory
    mode: 0700

- name: Create configuration directory
  file:
    path: /etc/etcd
    state: directory
    mode: 0755

- name: Copy certificates into configuration directory
  copy:
    src: configuration/{{ item }}
    dest: /etc/etcd/{{ item }}
    mode: 0644
  with_items:
    - ca.pem
    - kubernetes-key.pem
    - kubernetes.pem

- name: Install etcd service configuration
  copy:
    src: etcd.service
    dest: /etc/systemd/system/etcd.service
    mode: 0644

- name: Enable etcd service
  systemd:
    name: etcd
    daemon_reload: yes
    enabled: yes
    state: stopped

- name: Install etcd service configuration into cloud-init
  copy:
    src: etcd-bootstrap.cfg
    dest: /etc/cloud/cloud.cfg.d/etcd-bootstrap.cfg
    mode: 0644

- name: Install j2cli for execution of etcd-bootstrap bootcmd
  pip: name=j2cli